# Use an official Python runtime as a parent image
FROM python:3.9-slim AS base

# Set the working directory in the container
WORKDIR /app

# Copy the model training script into the container
COPY src/ .

# Install Scikit-Learn and joblib
RUN pip install --no-cache-dir -r requirements.txt

# Run the script when the container launches
HEALTHCHECK CMD python -c "import joblib" || exit 1
ENTRYPOINT  ["python", "main.py"]


