name: Train and save model to GCS

on:
  # Trigger the workflow when a pull request targets main
  # push:
  #   branches:
  #     - main

  # Optional: allow manual runs from the Actions tab
  workflow_dispatch:
  
jobs:
  lint_and_format:
    name: Lint and Format Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Auto-format code with Black
        run: black Lab3_Github

      - name: Run flake8
        run: flake8 Lab3_Github --max-line-length=100
        
  train_and_save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Get cache dir 
        id: pip-cache-dir
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir}}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Lab3_Github/requirements.txt
      
      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Train and save model
        run: |
          python Lab3_Github/train_and_save_model.py
      
